version: '3.3'
services:
  app:
    build: ./
    ports:
      - 80:${APP_PORT}
    environment:
      REDIS_HOST: redis
      DATABASE_HOST: postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CONNECT: postgres
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APP_PORT: ${APP_PORT}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_TOKEN: ${SLACK_TOKEN}
    networks:
      - webnet
  adminer:
    image: adminer:latest
    ports:
      - 7081:8080
    networks:
      - webnet
  postgres:
    image: postgres:11
    volumes:
      - data-volume:/data/db
    ports:
      - 7432:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_PASSWORD}
    networks:
      - webnet
networks:
  webnet:
volumes:
  data-volume:
